Apartments/Apartments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rent_website.urls')),
    path('/apartments_id:int', include('rent_website.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apartments/rent_website/urls.py
from django.urls import path
from . import views

app_name = "rent_website"

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path("<int:id>", views.details, name = 'details'),
    path("favorites", views.FavoriteView.as_view(), name = 'details'),
    path('login', views.login, name = 'login'),
    path('register', views.register, name = 'register'),
    path('search', views.search, name = 'search'),
    path('logout', views.logout, name='logout')



]

Apartments/rent_website/models.py
from django.db import models


class User(models.Model):

    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    username = models.CharField(max_length = 100)
    email = models.CharField(max_length = 100)
    password1 = models.CharField(max_length = 100)
    password2 = models.CharField(max_length = 100)
    def __str__(self):
        return self.username


class Apartments(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    description = models.TextField()
    type = models.CharField(max_length = 100)
    city = models.CharField(max_length = 100)
    district = models.CharField(max_length = 100)
    price = models.FloatField()
    size = models.IntegerField()
    floor = models.IntegerField()
    images = models.ImageField(upload_to ='static/rent_website/images')
    favorite = models.BooleanField()
    def __str__(self):
        return self.type + "-"+ self.city

Apartments/rent_website/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['']

Apartments/rent_website/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from .models import Apartments, User
from django.contrib.auth.models import auth, User
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login



class IndexView(generic.ListView):
    template_name ="rent_website/home.html"
    context_object_name = "all_apartments"
    def get_queryset(self):
        return Apartments.objects.all()

def details(request, id):
    apartment = Apartments.objects.get(id = id)
    return render(request, 'rent_website/details.html', {'apartment': apartment})

class FavoriteView(generic.ListView):
    template_name = "rent_website/favorites.html"
    def get_queryset(self):
        if Apartments.favorite == True:
            return Apartments.object.all()


def register(request):
    #form = UserCreationForm()
    if request.method == "POST":
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        password_confirmation = request.POST.get('password_confirmation')
        if password == password_confirmation:
            if User.objects.filter(username = username).exists():
               messages.info(request, "Username taken")
            elif User.objects.filter(email = email).exists():
               messages.info(request, "Email taken")
            else:
                user = User.objects.create_user(first_name = first_name, last_name = last_name, email = email, username = username, password = password,)
                user.save()
                print('user created')
                #return redirect("/login")
                return render(request, 'rent_website/login.html')

    else:
        return render(request, 'rent_website/register.html')



def login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username = username, password = password)
        if user is not None:
            auth.login(request, user)
            return redirect("/")
        else:
            messages.info(request, "User does not exist")
            return redirect("/login")
    else:

        return render(request, "rent_website/login.html")



def logout(request):
    auth.logout(request)
    return redirect("/")

def search(request):
    return render(request, 'rent_website/search.html')

Apartments/rent_website/templates/rent_website/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Sofia Property{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href='https://fonts.googleapis.com/css?family=Satisfy'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
    <link rel="stylesheet" type="text/css" href="{% static 'rent_website/style.css'%}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'rent_website:index' %}">Sofia Property</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class=""><a href="{% url 'rent_website:index' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Properties</a></li>
                <li>
                    <a href="{% url 'rent_website:search' %}">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp;Search
                    </a>
                </li>
            </ul>
             {% if user.is_authenticated %}
            <ul class="nav navbar-nav">

                <li>
                    <span class="" aria-hidden="true"></span>&nbsp;Hello {{username}}
                </li>
            </ul>
                {%endif%}
            <ul class="nav navbar-nav navbar-right">
                 {% if user.is_authenticated %}

                <li><a href="{% url 'rent_website:logout' %}"> Logout </a> </li>

                {% else %}

                <li>
                    <a href="{% url 'rent_website:login' %}">
                        <span class="glyphicon glyphicon-login" aria-hidden="true"></span>&nbsp;Sing in
                    </a>
                </li>
                <li>
                    <a href="{% url 'rent_website:register' %}">
                        <span class="glyphicon glyphicon-register" aria-hidden="true"></span>&nbsp; Register
                    </a>
                </li>

                {% endif %}
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Apartments/rent_website/templates/rent_website/details.html
{% extends 'rent_website/base.html' %}
{% block body %}
<h1> Details for apartment  </h1>


<img src="{{apartment.images}}" with = "500" height = "300">

<div class="details" >
<h3 style="font-family: papyrus">{{apartment.description}} <h3/>
<h3 style="font-family: papyrus">{{apartment.type}} <h3/>
<h3 style="font-family: papyrus">{{apartment.city}} <h3/>
<h3 style="font-family: papyrus">{{apartment.district}} <h3/>
<h3 style="font-family: papyrus">{{apartment.floor}}. етаж <h3/>
<h3 style="font-family: papyrus">{{apartment.price}} лв <h3/>

<div/>
{% endblock %}

Apartments/rent_website/templates/rent_website/favorites.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Favorites</title>
</head>
<body>

</body>
</html>

Apartments/rent_website/templates/rent_website/home.html
{% extends 'rent_website/base.html' %}
{% block body %}

<div class="container-fluid">
    <div class="row">
            {% for apartment in all_apartments %}
                <div class="col-md-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'rent_website:details' apartment.id %}">
                            <img src="{{ apartment.images }}" class="img-responsive" width="600" height="300">
                        </a>
                        <div class="caption">
                            <a href="{% url 'rent_website:details' apartment.id %}">
                            <h3>{{ apartment.type }} {{ apartment.city }}</h3>
                                </a>
                            <h5>{{apartment.price}} lv</h5>

                        </div>
                    </div>
                </div>

{%endfor%}

        {%endblock%}

Apartments/rent_website/templates/rent_website/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'rent_website/style.css'%}"/>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Apartment list</title>
</head>
<body>
{% if all_apartments %}
    <ul style="list-style-type:none">
        {% for apartment in all_apartments %}
        <li>
        <a href="{% url 'rent_website:details' apartment.id %} ">
            <img src="{{apartment.images}}" width=400" height="170">
            <div> {{apartment.type}} - {{apartment.city}}  </div>
        </a>
        </li>
        {% endfor %}
    </ul>
{% else %}
<h3> You don't have anything to display </h3>
{% endif %}

</body>
</html>

Apartments/rent_website/templates/rent_website/login.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->



<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <div class="fadeIn first">
      <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
    </div>

    <!-- Login Form -->

    <form method = "POST" action="login">
    {%csrf_token%}
      <input type="text" id="login" class="fadeIn second" name="login" placeholder="login">
      <input type="text" id="password" class="fadeIn third" name="login" placeholder="password">
      <input type="submit" class="fadeIn fourth" value="Log In">
    </form>

    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password?</a>
    </div>

  </div>
</div>

<div>
	{% for message in messages%}

	<h4> {{message}} </h4>

	{%endfor%}

</div>

Apartments/rent_website/templates/rent_website/register.html
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<form action="register" method="POST">
	{% csrf_token %}
<div class="container">
        <div class="row centered-form">
        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
        	<div class="panel panel-default">
        		<div class="panel-heading">
			    		<h3 class="panel-title">Please sign up for Sofia Properties </h3>
			 			</div>
			 			<div class="panel-body">
			    		<form role="form">
			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			                <input type="text" name="first_name" id="first_name" class="form-control input-sm" placeholder="First Name">
			    					</div>
			    				</div>
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="text" name="last_name" id="last_name" class="form-control input-sm" placeholder="Last Name">
			    					</div>
			    				</div>
			    			</div>
                          <div class="panel-body">
			    		<form role="form">
			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			                <input type="text" name="username" id="username" class="form-control input-sm" placeholder="Username">
			    					</div>
			    				</div>

			    			<div class="form-group">
			    				<input type="email" name="email" id="email" class="form-control input-sm" placeholder="Email Address">
			    			</div>

			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="password" name="password" id="password" class="form-control input-sm" placeholder="Password">
			    					</div>
			    				</div>
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    						<input type="password" name="password_confirmation" id="password_confirmation" class="form-control input-sm" placeholder="Confirm Password">
			    					</div>
			    				</div>
			    			</div>
			    			
			    			<input type="submit" value="Register" class="btn btn-info btn-block">
			    		
			    		</form>
			    	</div>
	    		</div>
    		</div>
    	</div>
    </div>
	</form>

<div>
	{% for message in messages%}

	<h4> {{message}} </h4>

	{%endfor%}

</div>

Apartments/rent_website/templates/rent_website/reserve.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap 4 Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
 <link rel="stylesheet_2" href= "static/rent_website/style.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class = "nav justify-content-end">
    <li class="nav-item text: white">
      <a class="nav-link" href="{% url 'rent_website:index' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'rent_website:sign_in' %}">Sing in</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Register</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#"><button class="btn btn-success" type="submit">Search</button> </a>
    </li>
  </ul>
</nav>

<div class="container-fluid pt-3 bg-dark text-white padding-right: 15px">
  <div class="row">
      <div class="col-sm">
          {% for apartment in all_apartments %}
          <a href="{% url 'rent_website:details' apartment.id %}">
          <img src="{{apartment.images}}" class="rounded" width=400" height="230">
          <p style = "font-family: cursive ; color:azure"> {{apartment.type}}  {{apartment.city}} - {{apartment.price}} lv  <p/>

          {% endfor %}
      </div>

  </div>
</div>

</body>
</html>

Apartments/rent_website/templates/rent_website/search.html
{% extends 'rent_website/base.html' %}
{% block body %}

<div class="form-group">
  <label for="sel1">Населено място:</label>
  <select class="form-control" id="sel1">
  <option>Банишора <option/>
    <option>Красно село<option/>
    <option>Сухата река<option/>
    <option>Гео Милев<option/>
    <option>Люлин<option/>
    <option>Ситняково<option/>
    <option>Красна поляна<option/>
    <option>Сердика<option/>
    <option>Лагера<option/>
    <option>Зона Б-5<option/>
    <option>Б-18<option/>

    </select>

</div>

<div class="form-group">
  <label for="sel1">Тип:</label>
  <select class="form-control" id="sel1">
  <option>Едностаен <option/>
    <option>Двустаен<option/>
    <option>Тристаен<option/>
    <option>Четиристаен<option/>
    <option>Многостаен<option/>
    <option>Мезонет<option/>
    <option>Ателие<option/>
    <option>Къща<option/>
    <option>Етаж от къща<option/>

    </select>

</div>

<form class="form-inline">
  <div class="form-group">
    <label for="min_price">Минимална цена:</label>
    <input type="text" class="form-control" id="min_price">
  </div>
  <div class="form-group">
    <label for="max_price">Максимална цена:</label>
    <input type="text" class="form-control" id="max_price">
  </div>
  <form/> <br> <br> <br>

  <form class="form-inline">
  <div class="form-group">
    <label for="min_size">Минимална квадратура:</label>
    <input type="text" class="form-control" id="min_size">
  </div>
  <div class="form-group">
    <label for="max_size">Максимална квадратура:</label>
    <input type="text" class="form-control" id="max_size">
  </div>
  <form/> <br> <br> <br>

    <form class="form-inline">
  <div class="form-group">
    <label for="min_floor">Етаж от:</label>
    <input type="text" class="form-control" id="min_floor">
  </div>
  <div class="form-group">
    <label for="max_floor">Етаж до:</label>
    <input type="text" class="form-control" id="max_floor">
  </div>
  <form/> <br> <br> <br>

  <button type = submit> Търси  </button>
{%endblock%}

Apartments/rent_website/templates/rent_website/sign_in.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <div class="fadeIn first">
      <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
    </div>

    <!-- Login Form -->
    <form method = "POST" action="login">
      <input type="text" id="login" class="fadeIn second" name="login" placeholder="login">
      <input type="text" id="password" class="fadeIn third" name="login" placeholder="password">
      <input type="submit" class="fadeIn fourth" value="Log In">
    </form>

    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password?</a>
    </div>

  </div>
</div>

<div>
	{% for message in messages%}

	<h4> {{message}} </h4>

	{%endfor%}

</div>